name: RW — Backup MariaDB 

on:
  workflow_call:
    inputs:
      github_env:
        type: string

      database_host:
        type: string
        required: true

      database_name:
        type: string
        required: true

      database_user:
        type: string
        required: true

      options:
        type: string
        required: false

      storage_account_name:
        type: string
        required: true

      storage_container_name:
        type: string
        required: true
      
      backup_file_name:
        type: string
        required: true

    secrets:
      database_password:
        required: true
      
      azure_login_creds:
        required: true

defaults:
  run:
    shell: bash

jobs:
  backup:
    name: 'Backup MariaDatabase'
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.github_env  }}

    steps:

      - name: Create
        run: |
          PASSWORD='${{ secrets.database_password }}' mysqldump -q \
          --user=${{ inputs.database_user }} --lock-tables --databases cca_quote_dev > /data/backup/db1.sql

      - name: Azure login
        uses: Azure/login@v1
        with:
          creds: '${{ secrets.azure_login_creds }}'

      - name: Upload
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload \
            --account-name ${{ inputs.storage_account_name }} \
            --container-name ${{ inputs.storage_container_name }} \
            --file ${{ inputs.backup_file_name }}
